language: node_js
node_js:
  - "10"
sudo: true

before_install:
  - npm i -g npm@6.2.0

install:
  - npm install gitbook-cli -g

script:
  - gitbook install ./gitbook
  - gitbook build ./gitbook

deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  bucket: "algorithm.softcon.xyz"
  local_dir: ./gitbook/_book
  acl: public_read
  skip_cleanup: true

notifications:
  - on_success: never
  - on_failure: always