language: node_js
node_js:
  - "10"
sudo: true

before_install:
  - npm i -g npm@6.2.0

install:
  - npm install gitbook-cli -g

script:
  - gitbook build

notifications:
  - on_success: never
  - on_failure: always